[build]
  base = "frontend"
  command = "cd .. && npm install && cd netlify/functions && npm install && cd ../../frontend && npm run build"
  publish = "dist"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
